# version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/idurarDB
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
