name: Deploy Full Stack App

on:
  push:
    branches:
      - main  # change this to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name:  Login to DockerHub (optional, only if pushing to DockerHub)
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name:  Build and push Docker images (optional)
      #   run: |
      #     docker build -t yourdockeruser/frontend-app ./frontend
      #     docker build -t yourdockeruser/backend-app ./backend
      #     # docker push yourdockeruser/frontend-app
      #     # docker push yourdockeruser/backend-app

      - name:  Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/your/app
            git pull origin main
            docker-compose down
            docker-compose up --build -d
